### ISSUE TITLE
Full node code release timeline?

### ISSUE THREAD

**Issue by helinwang** [binance-chain/go-sdk#10]
Hi,

Thanks for the release! I was wondering when will the full node code be released so that we can play with it?

Currently making an order is only available with API calls, is making orders via peer-to-peer communication between client full node and validators going to be supported?

Thanks!

**Comment by notatestuser** [comment]
The binary will be ready next week, code soon after. We are waiting for some audits to be completed prior to the node code release.

**Comment by helinwang** [comment]
Thanks!
