### ISSUE TITLE
rpc calls to public nodes

### ISSUE THREAD

**Issue by lukekhamilton** [binance-chain/go-sdk#100]
I am trying to use the following example code on a public node and its not working, however it works when I run a node locally. 

Can someone tell is rpc calls blocked on public nodes? Or am I missing something? Thanks

```
nodeAddr := "https://seed1.longevito.io"
c := rpc.NewRPCClient(nodeAddr,types.TestNetwork)
status, err := c.Status()
```

**Comment by huangsuyu** [comment]
Hello, @lukekhamilton 

I think that public node is on mainnet, not testnet. please change the network type.
