### ISSUE TITLE
Question about the result of a success/fail in transaction

### ISSUE THREAD

**Issue by leeheejoo** [binance-chain/go-sdk#109]
In the transaction section below, can I find out what is the result of the transaction success or fail?

{
"jsonrpc": "2.0",
"id": "",
"result": {
"hash": "AB1B84C7C0B0B195941DCE9CFE1A54214B72D5DB54AD388D8B146A6B62911E8E",
"height": "7560096",
"index": 0,
"tx_result": {
"data": "eyJvcmRlcl9pZCI6IjgxM0U0OTM5RjE1NjdCMjE5NzA0RkZDMkFENERGNThCREUwMTA4NzktNDMifQ==",
"log": "Msg 0: ",
"tags": [
{
"key": "YWN0aW9u",
"value": "b3JkZXJOZXc="
}
]
},
"tx": "2wHwYl3uCmPObcBDChSBPkk58VZ7IZcE/8KtTfWL3gEIeRIrODEzRTQ5MzlGMTU2N0IyMTk3MDRGRkMyQUQ0REY1OEJERTAxMDg3OS00MxoNWkVCUkEtMTZEX0JOQiACKAEwwIQ9OJBOQAEScAom61rphyECE5vdld5ywirCorD4eFOxzKLorfnFikponHXTJjATRBoSQFmMOnTcCNgtl2aO01I6EFoq+3UsW+NNCftfMVjVXbL1RaJGYmPPgPAtEYTdUO/E2KY2omKQmmMuvt3qpCbAkrIY0uUYICo="
}
}

**Comment by huangsuyu** [comment]
Hello, @leeheejoo
You can use this function to get transaction result: https://github.com/binance-chain/go-sdk/blob/master/client/basic/basic.go#L68
