### ISSUE TITLE
Deposit Proposal - Signature verification failed

### ISSUE THREAD

**Issue by cgebe** [binance-chain/go-sdk#15]
When trying to deposit for a listing proposal i get the following error msg:

```
{"code":65540,"message":"{\"codespace\":1,\"code\":4,\"abci_code\":65540,\"message\":\"signature verification failed\"}"}
```

Other commands work as usual.

**Comment by cgebe** [comment]
I guess the error is related to the asset not fully listed. When i try to create an order with the asset i get the same error.

The signed message includes the `baseAssetSymbol`, this is causing a verification failure on the node side failure since the asset is not listed yet:
```
	newOrderMsg := msg.NewCreateOrderMsg(
		fromAddr,
		orderId,
		op,
		common.CombineSymbol(baseAssetSymbol, quoteAssetSymbol),
		price,
		quantity,
	)
```

Same goes for the deposit?

**Comment by guagualvcha** [comment]
close in https://github.com/binance-chain/go-sdk/pull/17
