### ISSUE TITLE
我现在的Mac系统是13.2.1，报错了。能否修复一下这个bug。感谢了

### ISSUE THREAD

**Issue by shuaizhang66** [binance-chain/go-sdk#182]
# github.com/zondax/hid
In file included from ../../pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:38:
../../pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:133:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here

**Comment by isaacyuno** [comment]
Will get the team to update to 0.9.1 in code
