### ISSUE TITLE
How to decode transation Data?

### ISSUE THREAD

**Issue by kanliyong** [binance-chain/go-sdk#42]
Hello boys

I use client.GetTx( *hash ) to fetch **Transaction**,

> 35EE4D73437D42F8F6E843F456C0CBC55E8D4D21AF8344467A124ED4DE655934

then i get the result :
```json
{
    "result": {
        "hash": "35EE4D73437D42F8F6E843F456C0CBC55E8D4D21AF8344467A124ED4DE655934",
        "log": "Msg 0: ",
        "data": "Tx{D301F0625DEE0A4E2A2C87FA0A230A14552E2B1CE6B2ECBFE50AD72B9DF9B8A9412BCF44120B0A03424E421080E497D01212230A148EA70D7D2EA8A14BA2B33D18D5DFBD6FAE0A6EA8120B0A03424E421080E497D01212700A26EB5AE98721024BE751508AE3FEDA03B4EAE7D01C5E16EE5920B3490CCA524251B7537B90038F12408559D2EA38302E137B93097495A22D8058D0AE8FD852E575D986517371D1A56454BA4DA491B4C13CD7063A7BBD48A065C7E617BBEE0A3E36851E8894DD266C3A18D7F50220321A093130363233353332362001}",
        "code": 0
    },
    "error": null,
    "id": 1
}
```

My question is  How To decode the Data 

> Tx{D301F0625DEE0A4E2A2C87FA0A230A14552E2B1CE6B2ECBFE50AD72B9DF9B8A9412BCF44120B0A03424E421080E497D01212230A148EA70D7D2EA8A14BA2B33D18D5DFBD6FAE0A6EA8120B0A03424E421080E497D01212700A26EB5AE98721024BE751508AE3FEDA03B4EAE7D01C5E16EE5920B3490CCA524251B7537B90038F12408559D2EA38302E137B93097495A22D8058D0AE8FD852E575D986517371D1A56454BA4DA491B4C13CD7063A7BBD48A065C7E617BBEE0A3E36851E8894DD266C3A18D7F50220321A093130363233353332362001}

**Comment by guagualvcha** [comment]
You can try with: 
```
import (
	"flag"
	"fmt"
	"github.com/binance-chain/go-sdk/client/rpc"
	"github.com/binance-chain/go-sdk/types/tx"
)
tx, err := rpc.ParseTx(tx.Cdc, txResult.Tx)
```

**Comment by kanliyong** [comment]
> You can try with:
> 
> ```
> import (
> 	"github.com/binance-chain/go-sdk/client/rpc"
> 	"github.com/binance-chain/go-sdk/types/tx"
> )
> tx, err := rpc.ParseTx(tx.Cdc, txResult.Tx)
> ```

Thank you very much ,
I complete with this
```go
        result, err := client.GetTx( *txhash )
	if err != nil {
		return
	}
	var data string
	_, err = fmt.Sscanf(result.Data, "Tx{%s}", &data)
	if err != nil {
		return
	}

	b, err := hex.DecodeString(data)
	transaction, err := bnbRpc.ParseTx(tx.Cdc, b)

	if result != nil {
		*reply = transaction
	}
```
