### ISSUE TITLE
Generated Key Store Address Doesn't Match With Displayed Address on binance.org

### ISSUE THREAD

**Issue by touhonoob** [binance-chain/go-sdk#46]
Reproduce:

1. Generate a keystore and export it as json file using `keyManager.ExportAsKeyStore(...)` and check its address using `keyManager.GetAddr().String()`
2. Load the keystore on binance.org
3. Compare the address displayed from the SDK and Binance DEX

**Comment by huangsuyu** [comment]
@touhonoob the keystore mismatch with binance.org going to fixe in https://github.com/binance-chain/go-sdk/pull/48 .
