### ISSUE TITLE
Cannot Import Keystore JSON Exported From binance.org

### ISSUE THREAD

**Issue by touhonoob** [binance-chain/go-sdk#47]
Reproduce:

1. Create a new wallet on binance.org and save it as keystore json
2. Import the keystore json using `NewKeyStoreKeyManager`
3. Shows decryption error

**Comment by guagualvcha** [comment]
@touhonoob  the keystore mismatch with binance.org going to fixe in https://github.com/binance-chain/go-sdk/pull/48.
