### ISSUE TITLE
KeyManager - testnet tbnb addresses

### ISSUE THREAD

**Issue by camstuart** [binance-chain/go-sdk#51]
Hi, I would like to understand test / prod wallet addresses better

I am creating a wallet like so:

```Golang
km, err := keys.NewKeyManager()
```

And the public address can be obtained with:

```Golang
address := km.GetAddr() // "bnb1683m5xkxa3p69yagrpdsvkp94xvx6utj863596"
```

But the testnet address is actually:
`tbnb1683m5xkxa3p69yagrpdsvkp94xvx6utjf0cs9t`

In the Go sdk, how do I derive or obtain the testnet address?

**Comment by huangsuyu** [comment]
hello, @camstuart 
You need to specify the network type to testnet:
```
//-----   Init sdk  -------------
client, err := sdk.NewDexClient("testnet-dex.binance.org", types.TestNetwork, keyManager)
```

**Comment by guagualvcha** [comment]
or you can set global var `types.Network = types.TestNetwork`

**Comment by hoangphuongcs** [comment]
Thank you so much! I need it to!
