### ISSUE TITLE
How to decode the response  of ABCIQuery?

### ISSUE THREAD

**Issue by Brochao** [binance-chain/go-sdk#76]
When get account balance by node RPC API, the ABCIQuery's path "/store/acc/key" returns amino-encoded string. 
`S9xMJwqZAQoU2h8pqmnHMwEZj0aev9+Dl6RdX/gSCwoDQk5CEMW8zopAEg4KCEJUQ0ItMURFELDqARIRCgdDT1MtMkU0EICS+6+G2QgSEAoHR0lWLTk0RRCAoLeH6QUSEAoJVVNEU0ItMUFDELC2wwEaJuta6YchAxtKZAZBHnTpu+kOOTEacbgw1TB14nwSIZIEBc40M+6xIIH5Aij2Pg==`

after base-64 decode, I tried to decode the response to struct 
`type ResponseQuery struct {
    Code                 uint32
    Log                  string
    Info                 string
    Index                int64
    Key                  []byte
    Value                []byte
    Proof                *merkle.Proof
    Height               int64
    Codespace            string
}`
but failed.

so how can I get the JSON result shown in  [document](https://docs.binance.org/api-reference/node-rpc.html#619-abciquery) ?

**Comment by huangsuyu** [comment]
Hello, @Brochao 

Can you take a look at the code here: https://github.com/binance-chain/go-sdk/blob/3f52c489082684ec2384acdcb73ffa8ad940ccf7/client/rpc/dex_client.go#L107

Thanks!
