### ISSUE TITLE
Compile Error when use "github.com/binance-chain/go-sdk/"

### ISSUE THREAD

**Issue by WangChao4055** [binance-chain/go-sdk#86]
we use  github.com/binance-chain/go-sdk v1.1.1-0.20190821064547-83eefca364c2 in go mod,but Still have the following error：
   go: downloading github.com/binance-chain/go-sdk v1.1.1-0.20190821064547-83eefca364c2
# command-line-arguments
/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//IOKit.framework/IOKit.tbd and library file /System/Library/Frameworks//IOKit.framework/IOKit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//IOKit.framework/IOKit.tbd and library file /System/Library/Frameworks//IOKit.framework/IOKit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
duplicate symbol _hid_read_timeout in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_get_feature_report in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_send_feature_report in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_exit in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_init in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_error in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_free_enumeration in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_open in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_open_path in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_get_product_string in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_get_manufacturer_string in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_get_serial_number_string in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_get_indexed_string in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_set_nonblocking in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_write in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_enumerate in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_close in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _hid_read in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000031.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000035.o
duplicate symbol _gowchar_set in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000032.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000038.o
duplicate symbol _gowchar_get in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000032.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000038.o
duplicate symbol _SIZEOF_WCHAR_T in:
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000032.o
    /var/folders/89/c20jnwtx7x9_lvc7782yl6x00000gn/T/go-link-624481362/000038.o
ld: 21 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by WangChao4055** [comment]
This problem occurs when used with the eth SDK

**Comment by WangChao4055** [comment]
[sdk_demo.zip](https://github.com/binance-chain/go-sdk/files/3559734/sdk_demo.zip)
Upload a simple demo that will reproduce this problem in this demo

**Comment by HaoyangLiu** [comment]
Can you share the detailed steps to reproduce this issue?

**Comment by WangChao4055** [comment]
Directly running the main.go file inside the sdk_demo will appear

**Comment by guagualvcha** [comment]
Because go-sdk and eth-sdk both import  `github.com/zondax/hid` which contains c lib,  so that cause `duplicate symbol _hid_read_timeout `, there is one solution, fork the repo and add following in go.mod:
```
replace github.com/zondax/hid => github.com/{your org}/hid v0.9.1-0.20190807012304-e1ffd6f0a3cc
```

**Comment by WangChao4055** [comment]
> Because go-sdk and eth-sdk both import `github.com/zondax/hid` which contains c lib, so that cause `duplicate symbol _hid_read_timeout `, there is one solution, fork the repo and add following in go.mod:
> 
> ```
> replace github.com/zondax/hid => github.com/{your org}/hid v0.9.1-0.20190807012304-e1ffd6f0a3cc
> ```

I still have errors, and there is no commit of e1ffd6f0a3cc in the https://github.com/ZondaX/hid/commits/master project. Do you have an example of normal operation after the solution?

**Comment by yutianwu** [comment]
you can refer to this branch: https://github.com/yutianwu/hid/tree/disable

**Comment by WangChao4055** [comment]
Ok, let me try
