### ISSUE TITLE
unmarshal to tx.StdTx failed

### ISSUE THREAD

**Issue by perfecting** [binance-chain/go-sdk#91]
hello：
I had a error when I use  go-sdk   
unmarshal to tx.StdTx failed after 6 bytes (error reading array contents: unrecognized prefix bytes 07921531):

**Comment by guagualvcha** [comment]
hi, can you post your code?

**Comment by perfecting** [comment]
Hello, I used  UnmarshalBinaryLengthPrefixed function.
var parsedTx tx2.StdTx
        err := cdc.UnmarshalBinaryLengthPrefixed(tx, &parsedTx)
        if err != nil {
            log.Error("UnmarshalBinaryLengthPrefixed tx error ", err)
        }

**Comment by HaoyangLiu** [comment]
How did you initialize `cdc`? Did you register all transaction types to it?

**Comment by lihuaizhong** [comment]
unmarshal to tx.StdTx failed after 7 bytes (error reading array contents: unrecognized prefix bytes B33F9A24)I happened at an altitude of 41455598 and after,What should I do?

**Comment by guagualvcha** [comment]
Please use cdc under this package:
![image](https://user-images.githubusercontent.com/7310198/68268029-934f6a00-008f-11ea-9140-a1a1550cfefc.png)

**Comment by perfecting** [comment]
thanks all .
