### ISSUE TITLE
Checksum mismatch error while downloading dependencies

### ISSUE THREAD

**Issue by apralat** [binance-chain/go-sdk#97]
Hey,
I am getting the following error while trying to download dependencies for the project:

> go: downloading github.com/btcsuite/btcd v0.20.0-beta
> verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
>         downloaded: h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=
>         sum.golang.org: h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
> 
> SECURITY ERROR
> This download does NOT match the one reported by the checksum server.
> The bits may have been replaced on the origin server, or an attacker may
> have intercepted the download attempt.
> 
> For more information, see 'go help module-auth'.

This issue should be fixed by upgrading btcd to v0.20.1-beta, here is more info on this:
https://github.com/btcsuite/btcd/issues/1487

I tried to do it myself, however some tests are failing after making this upgrade. Could you look into this? I can't verify if these tests are failing due to my change or not, since I can't run tests with previous version of btcd :)

**Comment by guagualvcha** [comment]
Thks for the report.  looks like the retag of btcd cause the issue. We will upgrade the version soon.

**Comment by guagualvcha** [comment]
hi @apralat  you may try release v1.2.1
