### ISSUE TITLE
Mismatch of docs/code of getting account balances

### ISSUE THREAD

**Issue by cbarraford** [binance-chain/go-sdk#98]
I noticed the documentation on how to query for account balances, and how the code does it in this repo is different.

In the code you're using `/account/<addr>`...
https://github.com/binance-chain/go-sdk/blob/master/client/rpc/dex_client.go#L144

But in the docs you're using `/store/acc/key`...
https://docs.binance.org/api-reference/node-rpc.html#619-abciquery

Which one is correct?

**Comment by guagualvcha** [comment]
the code is right. I will ask the community correct the doc

**Comment by huangsuyu** [comment]
I think both are correct. The way `dexclient` using is more accurate when the account states change very quickly.
